
#相机内参
fx: 721.5377
fy: 721.5377
cx: 609.5593
cy: 172.854

#手动添加的偏差
bias_x: -0.5 
bias_y: -0.5 
bias_z: -0.5

#雷达到相机的平移
t03: -0.004069766 
t13: -0.07631618 
t23: -0.2717806 

#雷达线束
rings: 64

#俯仰角（垂直方向角度范围）
lowerBound: -24.9
upperBound: 2.0

#雷达到相机的旋转矩阵
R_lidar2cam0_unbias:
  data: [0.007533745, -0.9999714, -0.000616602,
         0.01480249,  0.0007280733, -0.9998902,
         0.9998621,   0.00752379,   0.01480755]

search_r: 1.0
search_num: 10
search_r2: 1.0
search_num2: 1
search_r3: 10
search_num3: 1
x_max: 300.0
x_min: 5 #-1 # 1
y_min: -40
y_max: 40
z_min: -2.5
z_max: 5 #10
dis_threshold: 12 #30 #12 #3 the bigger the more points 60 90
angle_threshold: 100 #100 not used
deep_config: 80
point_r: 2
txtname: ../data0/list.txt
foldername: ../data0/
oxtsfolder: ../data0/

3frame_score: false
edge_features: false
line_features: true
filter_edge_features: false
filter_line_features: false
cluster_pointcloud: true
merge_frame: false
down_sample: false
save_pointcloud: true
save_calibrated_result: true
gauss_coresize: 5
edge_contours_size: 50
canny_threshold_mini: 50
canny_threshold_max: 100
normalize_config: 1100 # the bigger the thinner 3000
normalize_config_thin: 3600 # the bigger the thinner 3000
delete_ground: true
WindowSize: 0.5


max_distance: 30
debug_OnOff: false
  
show_num: 0
KKK: 1.0
many_or_one: 3
wait_msec: 13000

sigma: 50
step: 0.0001
alpha: 0.1
beta: 0.9
search_iter: 100
add_dis_weight: true
add_near_weight: false
overlap: true

T_cam02cam2:
  data: [1, 0, 0,0,
                0, 1,0,0,
                 0,0,1,0,
                 0,0, 0,1]

T_frame2frame0_pcs:
  data: [1, 0, 0,0,
                0, 1,0,0,
                 0,0,1,0,
                 0,0, 0,1]
T_frame2frame0_images:
  data: [1, 0, 0,0,
                0, 1,0,0,
                 0,0,1,0,
                 0,0, 0,1]


k1: -3.728755e-01
k2: 2.037299e-01
p1: 2.219027e-03
p2: 1.383707e-03
k3: -7.233722e-02


extract_pc_edges:
  nearest_num: 30
  edge_dis_th: 1.0
  planarity_th: 1.0
  ep_dis_th: 0.4
  neighbor_num: 5
  NMS_dis: 0.2
  show_all: false
  method: 6
  add_edge: false
  shuzhi_dis_th: 0.6
  angle_pixel_dis: 3
extract_img_edges:
  lambda: 0.05
  kappa: 1.0
test_sobel_weight:
  weight_x: 1.0
  weight_y: 1.0


rx2: 0.1
ry2: -0.1
rz2: -0.6
t032: -0.1040698 #-0.004069766   -0.0640698 -0.19407
t132: -0.1063162 #-0.07631618  -0.156316 -0.176316
t232: -0.281781 #-0.2717806 -0.311781 -0.371781
